# Generated by Django 3.0.5 on 2021-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
                ('job_desc', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='', max_length=50)),
            ],
        ),
    ]
