# Generated by Django 3.0.5 on 2021-03-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='', max_length=10, unique=True)),
                ('project_name', models.CharField(default='', max_length=30)),
                ('number_of_days', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('number_of_units', models.IntegerField()),
                ('budget', models.FloatField()),
                ('productivity', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='Project_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operations.Project'),
        ),
    ]
