# Generated by Django 3.0.5 on 2021-02-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('performance_score', models.IntegerField()),
                ('error', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('department_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hr.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='', max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
